# LAB-5_202001234

### Name : vivek harsora

### Group : 20

### the tools i used in the lab:

#### [mypy](https://mypy.readthedocs.io/en/stable/)

#### installation of the tool:

#### `pip install mypy`

## screen shot of the application of the tool:

![the screenshot of terminal](202001234.png "the screen-shot of the original test run")

### Reference to the repository:

##### [link of the repository](https://github.com/ThomasTheSpaceFox/Some-Small-python-pygame-apps)

#### error identification:

##### [File 1](https://github.com/ThomasTheSpaceFox/Some-Small-python-pygame-apps/blob/master/maxapacer.py)

- the error in the first file was the empty argument in the function `SysFont` .at line **12** in the file [maxapacer.py](https://github.com/ThomasTheSpaceFox/Some-Small-python-pygame-apps/blob/master/maxapacer.py).

- i gave a valid argument in that function to resolve the error.

##### [File 2](https://github.com/ThomasTheSpaceFox/Some-Small-python-pygame-apps/blob/master/lines1.py)

- in the second file there were two errors in [lines1.py](https://github.com/ThomasTheSpaceFox/Some-Small-python-pygame-apps/blob/master/lines1.py) at line **77** and line **78**.

- the cause of the errors was, the changing data type of a iterator and use of it as same iterator for other data type with using same data.

- i changed the iterator for one loop to resolve the errors.
